version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "task"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-26kiuaxm19u6"
s3_prefix = "task"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
